name: 'Gitbook Action Build'
on:
  push:
    branches:
      - main  # trigger branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2

    - name: Gitbook Action
      uses: GCS-ZHN/gitbook-action@v1.2.5
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: main
        publish_repo: GCS-ZHN/socube
